### ISSUE TITLE
php 8.4 or high

### ISSUE THREAD

**Issue by kaxias** [PrinsFrank/container#6]
https://github.com/PrinsFrank/container/blob/a8f4bba12f652a82c698c98f294737f6b0d4fc36/composer.json#L17
improve compatibility for future php
 "php": "^8.1",

**Comment by PrinsFrank** [comment]
Sorry, I was on holiday. On it!

**Comment by PrinsFrank** [comment]
@kaxias V0.2 is now out with support for PHP8.4!
